Initial work

diff --git a/Dockerfile-jessy b/Dockerfile-jessy
--- a/Dockerfile-jessy
+++ b/Dockerfile-jessy
@@ -1,4 +1,50 @@
 FROM debian:jessie
-RUN rm -rf /lib/systemd/  /usr/share/doc /usr/share/man
-RUN rm -rf /var/cache/debconf  /bin/systemd/*
-RUN rm -rf /usr/share/bash-completion  /lib/udev
+
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  systemd systemd-sysv sysv-rc sysvinit-utils
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  bash
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  bsdutils
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  passwd
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  netbase
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  diffutils
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  ncurses-base ncurses-bin
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  startpar
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  tzdata
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  sed
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  lsb-base
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  login
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  gzip
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  udev
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  mount
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  grep
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  dmsetup
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  base-passwd
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  util-linux
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libtext-charwidth-perl libtext-iconv-perl libtext-wrapi18n-perl
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libcryptsetup4
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libdevmapper1.02.1
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libsystemd0
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libgcrypt20
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libcomerr2
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  iproute2
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libsmartcols1
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libslang2
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libkmod2
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libmount1
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libblkid1
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libprocps3
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libudev1
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libustr-1.0-1
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  e2fslibs e2fsprogs
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libncurses5 libncursesw5
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libss2
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libcap2-bin
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libgpg-error0
+RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes   gnupg libreadline6 readline-common gpgv libapt-pkg4.12 libusb-0.1-4 libtinfo5 debian-archive-keyring
+
+
+#RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes   base-files coreutils dash debconf debconf-i18n debianutils findutils libacl1 libattr1 libaudit-common libaudit1  libbz2-1.0 libc-bin libc6 libcap2 libdb5.3 libdebconfclient0 liblzma5 libpam-modules libpam-modules-bin libpam-runtime libpam0g libpcre3  libreadline6 libselinux1 libsemanage-common libsemanage1 libsepol1 mawk multiarch-support  zlib1g
+
+#RUN rm -rf /usr/bin/* /var/cache/* /usr/sbin/* /bin/systemd/*
+RUN rm -rf  /usr/share/bash-completion /lib/udev  /usr/share/doc
+
+RUN du -sh / || :
